const menu = [
	{
		id: 1,
		title: 'Idly',
		category: 'breakfast',
		price: 15.99,
		img: 'https://indorehd.com/wp-content/uploads/2019/10/13-Best-Healthy-Indian-Breakfast-Recipes-Oats-Idli.jpg',
		desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
	},
	{
		id: 2,
		title: 'Meals',
		category: 'lunch',
		price: 13.99,
		img: 'https://feenix.co.in/wp-content/uploads/2017/12/veg-fare-2.jpg',
		desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
	},
	{
		id: 3,
		title: 'godzilla milkshake',
		category: 'shakes',
		price: 6.99,
		img: 'http://2.bp.blogspot.com/-p4KtjI9avZQ/UoOvGH3c_nI/AAAAAAAABU0/eSYIiWmR7BQ/s1600/FFT_Milo+Godzilla.jpg',
		desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
	},
	{
		id: 4,
		title: 'Dosa',
		category: 'breakfast',
		price: 20.99,
		img: 'https://www.eastcoastdaily.in/wp-content/uploads/2018/02/76-2-768x402.jpg',
		desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
	},
	{
		id: 5,
		title: 'biryani',
		category: 'lunch',
		price: 22.99,
		img: 'https://www.spiceindiaonline.com/wp-content/uploads/5.jpg',
		desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
	},
	{
		id: 6,
		title: 'oreo dream',
		category: 'shakes',
		price: 18.99,
		img: 'https://i.pinimg.com/originals/98/ef/aa/98efaa948a02b9694d1b330fc0561b6d.png',
		desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
	},
	{
		id: 7,
		title: 'poori',
		category: 'breakfast',
		price: 8.99,
		img: 'https://indianhealthyrecipes.com/wp-content/uploads/2018/06/Indian-breakfast-recipes-.jpg',
		desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
	},
	{
		id: 8,
		title: 'indian classic',
		category: 'lunch',
		price: 12.99,
		img: 'https://i.pinimg.com/originals/c2/0a/6b/c20a6b4d70daaefc2443bf503f669c02.jpg',
		desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
	},
	{
		id: 9,
		title: 'quarantine buddy',
		category: 'shakes',
		price: 16.99,
		img: 'https://www.sheknows.com/wp-content/uploads/2018/08/the-hobbitual-vert_glmtxh.jpeg',
		desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
	},
]
export default menu